a = [
    '<a href="#p100076816" class="quotelink">&gt;&gt;100076816</a><br>I don&#039;t really understand what you&#039;re trying to say. If birth rates are less than 2, the population decreases so the emissions decrease. Thats a natural state of de-growth. I&#039;m not arguing that people need fuel.<br><br>New taxes will &quot;change peoples behaviour&quot; but bringing in new people who wouldn&#039;t have had made much emissions where they came from for the sake of growth will cancel that out. Thats what makes no sense.<br><br>The corporations are just pushing for more &quot;consumers&quot;. More people to compete over the stuff they sell means more profits. It benefits no one else.<br><br>The west figured out its shit after 2 world wars where millions died. Let the 3rd world do the same. They don&#039;t need our help. In fact we&#039;er just gonna fuck them up more if we try.'
    '<a href="#p184126613" class="quotelink">&gt;&gt;184126613</a><br>Eye gunk forms around the eyes but it&#039;s not a problem for you because you wash them regularly. Same goes for earwax.'
    '<a href="#p154574502" class="quotelink">&gt;&gt;154574502</a><br><span class="quote">&gt;implying santa is satan</span>'
    '<a href="#p148976063" class="quotelink">&gt;&gt;148976063</a><br><br>And AR15 is not high powered - And AK47 or variant is DEFINITELY not high powered<br>There is no such thing as &quot;HIGH POWERED&quot;....PERIOD. When it comes to firearms.<br>Magazine capacity does not = &quot;HIGH .POWERED&quot;<br>semi auto capability does not = &quot;HIGH POWERED'
    'A FUCKING LEAF'
    '<a href="#p119907205" class="quotelink">&gt;&gt;119907205</a><br>http://www.strawpoll.me/12693783'
    '<a href="#p86639607" class="quotelink">&gt;&gt;86639607</a><br><span class="quote">&gt;Mfw there are already a lot of muslims in my city</span><br><span class="quote">&gt;Mfw i see them in malls</span><br><span class="quote">&gt;Mfw there are a lot of carts of &quot;Tacos Arabes&quot; (Arabian tacos) in the streets.</span><br><br>Thrust me, at least in my city the muslims likes to be here. There´s no much time left when they built a Mezquita.<br><br>Also, there are a lot of Indians too.'
    '<a href="#p104729486" class="quotelink">&gt;&gt;104729486</a><br>I disagree. I love the Dublin City Centre. I&#039;m a big city guy.']
b = ['a''b''c']